export const Author = {
  FULL_NAME: "Daniel Moore",
  NAME: "Dan",
  GITHUB: "https://github.com/Dan-Moore",
  EMAIL: "dan@moore-notes.com",
} as const;

export const Site = {
  TITLE: "Daniel Moore",
  DESCRIPTION: "Todo",
  /* DaisyUI Themes */
  THEMES: [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
    "caramellatte",
    "abyss",
    "silk",
  ],
  FONT_SIZES: [50, 75, 100, 125, 150, 175, 200, 225, 250, 275, 300],
  DEFAULT_FONT_SIZE: 100,
  FONT_FAMILIES: [
    "atkinson",
    "geist-mono",
    "ibm-plex-mono",
    "inter",
    "iosevka",
    "literata",
    "roboto",
    "space-grotesk",
  ],
  DEFAULT_FONT_FAMILY: "literata",
} as const;
